import { chromium } from '@playwright/test';
import { connection, hasRealCredential } from './config/environments';

if (!hasRealCredential(connection.username) || !hasRealCredential(connection.password)) {
  throw new Error('QA credentials are not configured for this environment');
}

(async () => {
  const browser = await chromium.launch({
    channel: 'chrome',
    headless: false,
  });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto(connection.url());
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill(connection.username);
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill(connection.password);
  await page.getByRole('button', { name: 'Log On' }).click();
  await page.getByRole('link', { name: 'New Request' }).click();
  await page.locator('#GeneralInfoDataModel_SelectedIntakeChannelId').selectOption('725060004');
  await page.locator('#GeneralInfoDataModel_SelectedSpecialtyId').selectOption('18aa7c0a-cadb-e011-b8c8-00155d652408');
  await page.locator('#GeneralInfoDataModel_SelectedPayerId').selectOption('cee77de3-167d-eb11-a2e1-edb83e5afb8e');
  await page.locator('label').click();
  await page.getByRole('link', { name: '21' }).click();
  await page.locator('#GeneralInfoDataModel_SelectedRequestPriorityId').selectOption('725060000');
  await page.locator('#GeneralInfoDataModel_SelectedRequestedById').selectOption('725060001');
  await page.getByRole('textbox', { name: 'Partial Name or Full NPI' }).click();
  await page.getByRole('textbox', { name: 'Partial Name or Full NPI' }).fill('IQ_UT_PF_080626029 IQ_UT_LF_080626029, MD');
  await page.getByText('IQ_UT_PF_080626029').click();
  await page.getByText('IQ_UT_PF_080626029').click();
  await page.getByText('IQ_UT_PF_080626029 IQ_UT_LF_080626029, MD @ IQ _Molina_UT_080726_029 of Molina').click();
  await page.getByRole('textbox', { name: 'Partial Last Name' }).click();
  await page.getByRole('textbox', { name: 'Partial Last Name' }).fill('IQ_UT_PF_080626029 IQ_UT_LF_080626029, MD');
  await page.getByText('IQ_UT_PF_080626029 IQ_UT_LF_080626029, MD', { exact: true }).click();
  await page.locator('#EditFromProviderInfoViewModel_SelectedPrimaryContactTitleId').selectOption('725060006');
  await page.locator('#PlaceOfServiceBaseViewModel_SiteOfAdministrationType').selectOption('725060000');
  await page.locator('#PatientInfoDataModel_FirstName').click();
  await page.locator('#PatientInfoDataModel_FirstName').fill('IQ_FN_08062026_2065');
  await page.locator('#PatientInfoDataModel_LastName').click();
  await page.locator('#PatientInfoDataModel_LastName').fill('IQ_LN_08062026_2065');
  await page.getByRole('row', { name: 'Date of Birth' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Date of Birth' }).getByLabel('').fill('12/18/1991');
  await page.locator('#EditRequiredPatientInfoViewModel > .nchPortalContainer > .ui-helper-clearfix > div').first().click();
  await page.getByText('View Request Page Review & Submit General InformationRequesting ProviderPlace').click();
  await page.locator('#PatientInfoDataModel_ExternalId').click();
  await page.locator('#PatientInfoDataModel_ExternalId').fill('IQ0806262065');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('IQ_FN_08062026_2065').click();
  await page.getByRole('button', { name: 'Select Member' }).click();
  await page.getByRole('textbox', { name: 'Feet' }).click();
  await page.getByRole('textbox', { name: 'Feet' }).fill('5');
  await page.getByRole('textbox', { name: 'Inches' }).click();
  await page.getByRole('textbox', { name: 'Inches' }).fill('6');
  await page.getByRole('textbox', { name: 'In lbs.' }).click();
  await page.getByRole('textbox', { name: 'In lbs.' }).fill('120');
  await page.getByRole('textbox', { name: 'ICD or Partial Name' }).click();
  await page.getByRole('textbox', { name: 'ICD or Partial Name' }).fill('d47.1');
  await page.locator('#ui-id-18').click();
  await page.getByRole('cell', { name: 'IC Request Received' }).nth(1).click();
  await page.locator('#EditClinicalInfoViewModel_SelectedEcog').selectOption('725060005');
  await page.locator('#EditClinicalInfoViewModel_IsNoClinicalQnA').check();
  await page.locator('#ServiceRequest_AdditionalComments').click();
  await page.locator('#ServiceRequest_AdditionalComments').fill('sat');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Service Item is required.').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('heading', { name: 'Service Items' }).click();
  await page.locator('#serviceItemSearchTerm').click();
  await page.locator('#serviceItemSearchTerm').fill('90562');
  await page.locator('#serviceItemSearchTerm').press('Enter');
  await page.locator('#serviceItemSearchTerm').fill('9');
  await page.locator('#serviceItemSearchTerm').click();
  await page.locator('#serviceItemSearchTerm').fill('93452');
  await page.locator('#serviceItemSearchTerm').press('Enter');
  await page.locator('#serviceItemSearchTerm').fill('j1442');
  await page.locator('#serviceItemSearchTerm').press('Enter');
  await page.getByText('J1442 FILGRASTIM G-CSF 1 MCG').click();
  await page.locator('#ServiceItemViewModels_0__ServiceItem_TypeOfMedication').selectOption('725060000');
  await page.getByRole('combobox', { name: 'Type to Search or Click to' }).click();
  await page.getByRole('option', { name: 'TAB PO DAILY X 30 DAYS' }).click();
  await page.locator('#ServiceItemViewModels_0__ServiceItem_Dosage_Id').selectOption('97f83028-2477-e311-8111-00155d1e5005');
  await page.locator('.tdTopborder > .datepicker-label').click();
  await page.getByRole('link', { name: '22' }).click();
  await page.locator('#ServiceItemViewModels_0__ServiceItem_NumberOfCycles').selectOption('1');
  await page.getByText('View Request Page Review & Submit General InformationRequesting ProviderPlace').click();
  await page.locator('#loggedInUser').click();
  await page.getByText('View Request Page Review & Submit General InformationRequesting ProviderPlace').click();
  await page.getByRole('contentinfo').click();
  await page.getByRole('contentinfo').click();
  await page.getByText('Characters Remaining: 3997').click();
  await page.getByText('View Request Page Review & Submit General InformationRequesting ProviderPlace').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.ui-widget-overlay').click();
  await page.locator('#PeerToPeerContactViewModel_ContactName').fill('sat');
  await page.locator('#PeerToPeerContactViewModel_DirectPhoneNumberExtension').fill('1234');
  await page.goto(connection.url('/IntakeHome/NewRequest/AuthorizationDecompResult'));
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('AR3919389').click();
  const page1 = await page1Promise;
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByText('Cancel / Void').click();
  const page2 = await page2Promise;
  await page2.close();
  await page1.getByRole('button', { name: 'ACTION' }).click();
  const page3Promise = page1.waitForEvent('popup');
  await page1.getByText('Cancel / Void').click();
  const page3 = await page3Promise;
  await page3.getByRole('checkbox', { name: 'Administrative error in Diagnosis Entered' }).check();
  await page3.getByRole('button', { name: 'SUBMIT' }).click();
  await page3.getByRole('button', { name: 'Ok' }).click();
  await page3.close();
  await page1.goto(connection.url('/determination/request/detail?authorizationRequestIdString=9a558e66-549d-f111-a835-7c1e5215bd7f'));
  await page.goto(connection.url('/Determination/Home/Index?areaId=7ae72752-e012-e911-80e6-005056855f9a'));
  await page1.close();
  await page.locator('#loggedInUser').getByText('Automation IC').click();
  await page.getByText('Log Off').click();
  await page.close();

  await context.close();
  await browser.close();
})();
